public enum CoffeeMachineState {
    GETTING_ACTION,
    GETTING_COFFEE_TYPE,
    GETTING_WATER_TO_REFILL,
    GETTING_MILK_TO_REFILL,
    GETTING_COFFEE_BEANS_TO_REFILL,
    GETTING_CUPS_TO_REFILL
}
